// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TecLibrasApi.Infra;

#nullable disable

namespace TecLibrasApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TecLibrasApi.Domain.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("TecLibrasApi.Domain.Models.Midia", b =>
                {
                    b.Property<int>("IdMidia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMidia"));

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdSinal")
                        .HasColumnType("int");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("TamanhoArquivo")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoMidia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlArquivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdMidia");

                    b.HasIndex("IdSinal");

                    b.ToTable("Midias");
                });

            modelBuilder.Entity("TecLibrasApi.Domain.Models.Sinal", b =>
                {
                    b.Property<int>("IdSinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSinal"));

                    b.Property<string>("TermoTi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdSinal");

                    b.ToTable("Sinais");
                });

            modelBuilder.Entity("TecLibrasApi.Domain.Models.SinalCategoria", b =>
                {
                    b.Property<int>("IdSinal")
                        .HasColumnType("int");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaIdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("SinalIdSinal")
                        .HasColumnType("int");

                    b.HasKey("IdSinal", "IdCategoria");

                    b.HasIndex("CategoriaIdCategoria");

                    b.HasIndex("SinalIdSinal");

                    b.ToTable("SinalCategorias");
                });

            modelBuilder.Entity("TecLibrasApi.Domain.Models.Midia", b =>
                {
                    b.HasOne("TecLibrasApi.Domain.Models.Sinal", "Sinal")
                        .WithMany("Midias")
                        .HasForeignKey("IdSinal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sinal");
                });

            modelBuilder.Entity("TecLibrasApi.Domain.Models.SinalCategoria", b =>
                {
                    b.HasOne("TecLibrasApi.Domain.Models.Categoria", "Categoria")
                        .WithMany("SinalCategorias")
                        .HasForeignKey("CategoriaIdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TecLibrasApi.Domain.Models.Sinal", "Sinal")
                        .WithMany("SinalCategorias")
                        .HasForeignKey("SinalIdSinal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Sinal");
                });

            modelBuilder.Entity("TecLibrasApi.Domain.Models.Categoria", b =>
                {
                    b.Navigation("SinalCategorias");
                });

            modelBuilder.Entity("TecLibrasApi.Domain.Models.Sinal", b =>
                {
                    b.Navigation("Midias");

                    b.Navigation("SinalCategorias");
                });
#pragma warning restore 612, 618
        }
    }
}
